CREATE TABLE READING (
  ID                  NUMBER PRIMARY KEY,
  ACCOUNT_NUMBER      VARCHAR2 NOT NULL,
  GAS_ID              NUMBER,
  ELEC_ID             NUMBER,
  ELEC_SMART_READ     NUMBER,
  GAS_SMART_READ      NUMBER
)